sudo: required

language: go

go:
  - 1.9.x

services:
  - docker
jobs: 
  include:
    - stage: go build
      script:
        - go build -o main.exe app.go
    - stage: docker build
      script: 
        - docker build -t turbosonic/api-gateway .
    - stage: docker push
      if: branch = master
      script:
        - docker tag turbosonic/api-gateway turbosonic/api-gateway:$TRAVIS_BRANCH