sudo: required

language: go

go:
  - 1.9.x

services:
  - docker

stages:
  - name: go build
    script:
      - go test -v ./tests
      - go build -o main.exe app.go
  - name: docker build
    script: 
      - docker build -t turbosonic/api-gateway .
  - name: docker push
    if: branch = master
    script:
      - docker tag turbosonic/api-gateway turbosonic/api-gateway:$TRAVIS_BRANCH