name: "/web/v1"
endpoints:
  - url: /posts
    methods:
      - method: GET
        destination:
          name: health
          host: http://localhost:3000
          url: /posts
  - url: /comments
    methods:
      - method: GET
        destination:
          name: get comments
          host: http://localhost:3000
          url: /comments
      - method: POST
        destination:
          name: add comment
          host: http://localhost:3000
          url: /comments
  - url: /profile
    methods:
      - method: GET
        destination:
          name: health
          host: http://localhost:3000
          url: /profile



