name: "/web/v1"
endpoints:
  - url: /posts
    methods:
      - method: GET
        roles:
          - "*"
        scopes:
          - "*"
        destination:
          name: health
          host: https://www.google.com
          url: /
  - url: /posts/:id
    methods:
      - method: GET
        roles:
          - "*"
        scopes:
          - "*"
        destination:
          name: health
          host: http://localhost:3000
          url: /posts/:id
  - url: /comments
    methods:
      - method: GET
        roles:
          - "*"
        scopes:
          - "*"
        destination:
          name: get comments
          host: http://localhost:3000
          url: /comments
      - method: POST
        destination:
          name: add comment
          host: http://localhost:3000
          url: /comments
  - url: /profile
    methods:
      - method: GET
        roles:
          - "*"
        scopes:
          - "*"
        destination:
          name: health
          host: http://localhost:3000
          url: /profile



