name: "/web/v1"
endpoints:
  - url: /example
    methods:
      - method: GET
        destination:
          name: example
          host: http://example-service
          url: /endpoint
  - url: /example/:id
    methods:
      - method: GET
        destination:
          name: example
          host: http://example-service
          url: /endpoint/:id



